jobs:
  workflow:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./action/run

name: Test

on:
  schedule:
    - cron: "20 2/3 * * *"
